### ISSUE TITLE
Remove background color of wording in Classic Tabs view

### ISSUE THREAD

**Issue by Shuggaloaf** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#104]
LOW PRIORITY
I know, I'm probably in the minority in that I prefer using the Classic Tabs view vs the Bookmarks. Just noticed this after updating. Could you remove the background from the tabs wording? (It's very faint, but it's there)
![image](https://user-images.githubusercontent.com/79543184/126555290-a1a1b0f7-beb5-42ee-b8c5-581593b35dbc.png)

Another (preferred) option would be to remove the background color and restyle that whole bar. Maybe make the bar color darker and the words lighter. Or whatever, just something to make it stand out more. 

Maybe like...
![image](https://user-images.githubusercontent.com/79543184/126556128-1410bce2-d7e1-455d-a93a-a57977a43934.png)
Or...
![image](https://user-images.githubusercontent.com/79543184/126556110-c1acbb7c-9b48-4e19-88e3-eb64a33d67b8.png)

Thanks!

**Comment by typhonrt** [comment]
This is a side effect of the dynamic background selection for the bookmark tab view which uses JQuery to add the background image to the bookmark tabs. This new feature allows FQL to adopt the system look and feel by default for the bookmark tabs, but presently also adds the background image to the classic tab view as well. 

The fix is a 1 line addition in `QuestLog.activateListeners` and modification to the if statement at the beginning to check if the navStyle is bookmarks; if so only then apply the dynamic background modification. 

Presently if you select "classic" for navigation style and disable dynamic bookmark background just above in module settings you will get the desired result. 

Totally open to RCOS making this change. I can provide more details if necessary.

**Comment by Shuggaloaf** [comment]
> Presently if you select "classic" for navigation style and disable dynamic bookmark background just above in module settings you will get the desired result.

Perfect -thanks Michael!

**Comment by typhonrt** [comment]
Released with `0.7.6` which is available now.
