### ISSUE TITLE
Provide access to control individual quests again.

### ISSUE THREAD

**Issue by atnoslen** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#105]
I see overall module setting controls in #58., however, I do  not see discussion on how to control individual quests and tasks.

For example, I was able to create a general purpose macro, such as

```
const id = args[0];

(async () => {
  await Quest.move(id, "active");

  Object.keys(game.questPreview).forEach(key => {
    game.questPreview[key].refresh();
  });
})();
```

Then using Advanced Macro's module create chat scripts such as

```
{{macro "Start Quest" "93kvfds0932"}}
```

I could then take that chat macro and embed in any journal entry, or quest description.  It allowed a very quick way to start a quest.

Similarly, completing tasks while following a journal script.

```
(async () => {
  const quest = Quests.get(questId);

  let index = 0;
  for (index = 0; index < quest.tasks.length; i++) {
    if (quest.tasks[index].name === taskName) {
      quest.tasks[index].completed = true;
      quest.tasks[index].failed= false;
      await quest.save();
     break;
    }
  }

  //quest.toggleTask();
  await quest.save();

  Object.keys(game.questPreview).forEach(key => {
    game.questPreview[key].refresh();
  });
})();
```

I have lost the functionality to control quests and tasks through macros and thereby embed in journal entries.  This seriously disrupts my flow having to take 2 to 4 clicks to perform an action rather than just creating the macro to perform an outcome based upon the party's result.

**Comment by typhonrt** [comment]
Hi @atnoslen... Thanks for dropping in and providing some insight into how you are using the Quest API. Indeed things have changed, but you can accomplish the same things just through a different mechanism. 

The first example of setting a quest status is now:
```
const questId = args[0];
const status = args[1];

const QuestAPI = game.modules.get('forien-quest-log').public.QuestAPI;

const quest = QuestAPI.DB.getQuest(questId);

await quest.setStatus(status);

QuestAPI.open({questId});
Hooks.call('ForienQuestLog.Open.QuestLog');
```

Invoke the above w/ Advanced Macros via:
`{{macro "Quest Status" "<QUEST_ID>" "<QUEST_STATUS>"}}`

Where the QUEST_STATUS is one of:
- active
- available
- completed
- failed
- inactive


The second example of setting a quest task status is now:
```
const questId = args[0];
const taskName = args[1];

const QuestAPI = game.modules.get('forien-quest-log').public.QuestAPI;

const quest = QuestAPI.DB.getQuest(questId);

for (let index = 0; index < quest.tasks.length; index++) {
   if (quest.tasks[index].name === taskName) {
      quest.tasks[index].completed = true;
      quest.tasks[index].failed= false;
      await quest.save();
      QuestAPI.open({questId});
      break;
   }
}
```

{{macro "Quest Task" "<QUEST_ID>" "<TASK_NAME>"}}

I named these two script macros above as `Quest Status` and `Quest Task`.

Do note that the `QuestAPI.open({questId});` and `Hooks.call('ForienQuestLog.Open.QuestLog');` call in either example is just a temporary solution to render the quest log and quest details again after the status / task change. 

The code that you had in your original examples only updated the local display and not the remote client displays. FQL uses a socket layer to update local and all connected clients, but in a future update very soon the socket layer will be minimized as the new QuestDB provides mechanisms for updating state that occur automatically and the view manager code will automatically render the appropriate views again, so you won't need the `QuestAPI.open` or `Hooks.call` in your macros. 

You may want to peruse your options in [QuestDBShim](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/blob/master/src/control/public/QuestDBShim.js) for external interaction with the new [QuestDB](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/blob/master/src/control/QuestDB.js). 

Let me know if you have any more questions otherwise I will close this issue tomorrow.

**Comment by atnoslen** [comment]
This works well, thank you.  I've been able to recreate my macros to handle quest interactions again (though I do need to refactor a bit, it's mostly minimal work so far).  I'd consider this closed for myself, outside of standard documentation purposes, which you've already established.

Thank you!

**Comment by typhonrt** [comment]
Right on.. Thanks for giving me an idea how folks might use the public API and hooking it up via Advanced Macros. 

When the  `0.8.0` version of FQL launches in the coming months the manual socket layer for control which isn't publicly available will be reduced and more automatic updating of the GUI will occur across all clients. You'll then be able to remove any of the manual redrawing aspects from your macros. 

If you have any thoughts on something you might find useful from the public API do feel free to drop by the [TyphonJS Discord](https://discord.gg/mnbgN8f) to brainstorm any ideas or get in touch via the issues forum here.
