### ISSUE TITLE
[BUG] Incompatibility with MEME - Moerills Expandable Markdown Editor

### ISSUE THREAD

**Issue by elena-v2** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#112]
**Module Version:** v0.7.5

**Describe the bug**
Anything that uses the editor, such as the quest description or GM notes, breaks with MEME.

**To Reproduce**
1. Install https://github.com/Moerill/fvtt-markdown-editor and make sure that it's being used as a replacement for WYSIWYG editors.
2. Open the quest log and edit a description of a quest or the GM notes.
3. Add some text and either press the save button within the editor panel.
4. Reopen the quest.

**Expected behavior**
Quest logs and GM notes save after being edited.

**Foundry Version:** 
0.8.8

**Additional context**
https://github.com/Moerill/fvtt-markdown-editor version 0.5.0

I'm under the understanding that this was an issue in the past that Moerill had addressed, but it seems to have broken at some point. I've bumped the issue on MEME's github issue tracker as well.

**Comment by typhonrt** [comment]
I'm going to have to put this in the "won't fix" category. @Moerill has been away from Foundry development for a bit and just returned so this particular module in fact say's it's not compatible above Foundry `0.7.0` which is a long time ago like last summer long time ago, so it probably just doesn't work well in general or is not updated to be fully integrated into the latest Foundry core. Though I understand he will probably make v0.8.x updates to various modules soon. 

See outdated warning: 
![image](https://user-images.githubusercontent.com/311473/128456796-dc8d9fe1-c55d-4578-8214-71ba2919a4da.png)

On a cursory look the replaced editor of course is not the TinyMCE editor and the underlying FormApplication in Foundry is not integrated with it seemingly. IE `saveEditor` of FormApplication is not called when the save button is pressed therefore `saveEditor` in FQL is not run and even if it was it wouldn't work because FormApplication would throw an error before even getting to FQL and FQL is built on the Foundry core support of TinyMCE and uses the TinyMCE API to retrieve the data from the editors to save. 

It doesn't look like the editor replacement has the same API, so things are just not going to work out of the box unless a shim is created by Moerill. It's not FQL's job to interface with a different editor replacement / API. 

I certainly encourage you to take a look at the latest `0.7.6` update to FQL launching later today as a lot of work has gone into making the TinyMCE editing experience quite deep and interactive and way better than the stock experience found in the journal editor. There will be an update / launch video going over the new functionality available for editing. 

At this time this can't be addressed though do get in touch w/ @Moerill to see if there are any updates planned for Foundry `v0.8.x` and beyond.
