### ISSUE TITLE
[BUG] ?? with img into the reward field?

### ISSUE THREAD

**Issue by Fridan99** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#115]
**Module Version:** v0.7.6

**Describe the bug**
Reward field. When I try to add an icon (image) to a reward for some reason the image appears black. 

**To Reproduce**
1. Go to 'reward field'
2. Click on '+ add Abstract'
3. Scroll down to 'try to change the img icon into the reward'

**Expected behavior**
I look forward to seeing the image I select

**Screenshots**
![2](https://user-images.githubusercontent.com/86131373/128645321-827c4d0f-47da-41a9-87c0-1a34054431ab.jpg)
![3](https://user-images.githubusercontent.com/86131373/128645322-d443418d-3c95-4587-985d-54d8b04aa5d6.jpg)

**Browser:**
NO. Native app.

**Foundry Version:** 0.8.8

**Game System:** 5e dnd

**Additional context**
-

**Comment by Fridan99** [comment]
ok, I just solved the problem. If the image has the symbols ( ), it is not reflected. Instead I changed ( ) to _
then the image DOES appear.

**Comment by typhonrt** [comment]
Hi @Fridan99! Thanks for submitting an issue. I can't duplicate this issue from either the browser or native client. I also put a test image in a world directory like it seems you tried from the image you posted and this works fine. Could you give me a little more information about the image you are trying to add. Or perhaps attach it to your comment, so that I can try the same image.

**Comment by typhonrt** [comment]
Ahh I see you this solved. Well thanks again for getting in touch.

**Comment by Fridan99** [comment]
> Ahh I see you got this solved. Well thanks again for getting in touch.

Yep, if the image has ( ) brackets in the image’s name, then the image is not displayed.... But that's Foundry's problem, not the module's. 

Just removing any ( ) from the image name, and you're done.
