### ISSUE TITLE
Allow more options for status change in specific tabs

### ISSUE THREAD

**Issue by happy-cujo** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#124]
Currently when you complete quest or mark it as failed your only option is to set it to Inactive or remove it.

If mistakes were made, in worst case scenario (moving from complete to failed or vice versa), you need to:
- mark quest as Inactive
- mark quest as In progress
- mark quest as Failed

That's 3 steps that you need to make when moving from complete/failed state the other one.

I could be missing something, but I don't see any reason why shouldn't you just change status (as GM) to the one that you're interested it.

So rendering a set of buttons with status change except the button that moves to the state from given tab would help getting rid of those additional steps.

**Comment by typhonrt** [comment]
Hi @happy-cujo. Thanks for the suggestion. I have added a completed status change button for failed quests and vice versa a completed button for failed quests so that a GM or trusted player w/ edit can move the quest between completed / failed without going to inactive -> active -> failed / completed.

**Comment by typhonrt** [comment]
Released in `0.7.7`
