### ISSUE TITLE
Remove "close" label on quest tracker header button... Was: ~~Support cleaner sheet title bar for Quest Tracker.~~

### ISSUE THREAD

**Issue by happy-cujo** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#128]
I wasn't able to pin point the reason for that but the "Close" text is not removed by the [Cleaner Sheet Title Bar](https://github.com/Daimakaicho/cleaner-sheet-title-bar) module.

The module plugs in into render hooks and remove any text that is associated with an icon.
For unknown to me reason the "Close" text from Quest Tracker isn't removed, but it looks like it should (there is a handler for renderApplication hook). 

The question is if it's Quest Tracked that is different from standard Application or the mentioned module is missing some handlers?

See how it's removed in Quest Log, but not in Quest Tracker:
![obraz](https://user-images.githubusercontent.com/15898113/132070875-d86c78db-c143-41e3-8335-2ecb7e084aac.png)

Edit. If it's not on this repo side, I'll create an issue on the other module repo.

**Comment by typhonrt** [comment]
Hi @happy-cujo. The quest tracker is not a standard application / popout window.

However, I recommend you suggest to the `cleaner sheet` module author a small modification will allow it to work with any application by providing a more generic HTML element selector. 

This [line in their module](https://github.com/Daimakaicho/cleaner-sheet-title-bar/blob/main/module/src/cleaner-sheet-title-bar.js#L20) can be changed from:
`const windowHeader = header.querySelector("header.window-header");`

to

`const windowHeader = header.querySelector("header:first-of-type");`

and it should work more broadly across all applications including custom ones like the quest tracker. 

Here is proof that this change works w/ FQL & the quest tracker:
![image](https://user-images.githubusercontent.com/311473/132080013-908e9214-ea13-4b61-b047-d017a3e664a2.png)

So, my suggestion is to contact that module author or submit a PR for the change mentioned above.

I'm going to mark this issue as `wontfix`.

**Comment by typhonrt** [comment]
I did make some adjustments to this custom Application CSS so that it does work with the cleaner sheet module without you submitting a PR to them, however because the quest tracker is mimicing a popout window there is no way to hook into the inner render functionality of the stock popout Window. It renders the entire template including header bar on every render. You can see what it will look like presently below w/ cleaner sheet enabled:
![fql-cleaner-sheet](https://user-images.githubusercontent.com/311473/132080846-8a2e0341-4f26-4314-a0e1-fe74e96865cc.gif)

Quite likely for the major `v0.8.x` series of releases I'll be switching to Svelte to render the reactive aspects of the quest log and quest tracker. When that update occurs the rendering of the entire template will be reduced or eliminated.

**Comment by typhonrt** [comment]
I suppose a bit of good news for you. I decided to remove the default "Close" label for this button.

**Comment by typhonrt** [comment]
Released in `0.7.7`
