### ISSUE TITLE
Broken release on foundryvtt.com

### ISSUE THREAD

**Issue by haskjold** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#136]
Hi

There seems to be a broken release (Version 0.3.17) on https://foundryvtt.com/packages/forien-quest-log

![forien_quest_log](https://user-images.githubusercontent.com/3763869/133941316-7605acbe-8b0d-4da5-a485-4b0c81ed854c.png)

These points to a different project for this release:
 Installation Link: https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/releases/download//module.json
Update Notes: https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/blob/v0.3.0/changelog.md

**Comment by typhonrt** [comment]
@haskjold Thanks for reporting. I too just noticed this very weird push to FQL. I didn't do it and since this is still managed through the league it seems to be a mistake by someone else working on Forien's Unidentified Items and they made a mistake in overwriting the package info for FQL. :O 

It is fixed now though and I verified that the download / install completes. I'll close this issue.
