### ISSUE TITLE
QuestLog.render can't find partials [BUG]

### ISSUE THREAD

**Issue by Tristan-Goucher** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#17]
**Module Version:** v0.5.4

**Describe the bug**
Both via macro and via the button at the footer of the Journal tab in the sidebar, attempts to open the Quest Log fail. Looking at the console reports an error where it can't find the partial tab.html file. I've verified the file exists and I'm using the electron app, not Forge.

**To Reproduce**
1. Go to Journals tab or Macros directory
2. Click on 'Quest Log' button in Journals tab or execute the macro
3. Open Console and open the error message marked "d"

**Expected behavior**
All HTML files are found so that the quest log can be rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/72034470/112885421-97659880-9085-11eb-8484-be91a977a0d6.png)

**Browser:**
 - Electron desktop app

**Foundry Version:** 
0.7.9

**Game System:** 
PF1E 0.77.19

**Additional context**
I've used "Find the culprit!" with everything else disabled and the problem persists.

**Comment by xdy** [comment]
Hmm. I can't reproduce it. What I tried to reproduce it was:
On my windows 10 computer, using Foundry 0.7.9 and dnd5e 1.2.4 as the game master on the electron app I created a new world, added *only* quest log, added a scene, opened the quest log from the 'pen icon' on the left, opened the floating quest window using the icon below that, both worked for me (i.e. the dialogs opened, and I got no exceptions in the console).
I also in the same world opened the quest log using the button on the journals tab, which also worked for me.
I also tried the same in my regular game world, which worked.
I also tried the above using a newly created world on a newly installed PF1E 0.77.19, and everything worked.
I then logged in to the pf1 world as a player (from firefox), and tried the same, which also worked for me.
I also retested the above in a new pf1 world after removing and reinstalling the quest log module, which made no difference for me.
So, I need some more help to reproduce this bug in order to fix it.

**Comment by xdy** [comment]
One thing you can try, just in case it's a problem with your local install is to first remove the module, and then install it again.
Yes, that is a 'fix' on the level of 'have you tried restarting it?`, but, eh, it sometimes works, so worth a shot. :)

**Comment by Tristan-Goucher** [comment]
Find the Culprit failed me.

I tried a new world after your comment and it worked. After several hours of testing, it breaks _only_ if the Right-Click Enabler module is installed... somehow.

Sorry for the false alarm.

**Comment by Shayulghul** [comment]
I know this issue was closed, but I'm still having the same issue with 5.6, FVTT 7.9, and Chrome Version 89.0.4389.114. Should I start a new bug?


> One thing you can try, just in case it's a problem with your local install is to first remove the module, and then install the latest version (currently 0.5.6).
> Yes, that is a 'fix' on the level of 'have you tried restarting it?`, but, eh, it sometimes works, so worth a shot. :)
