### ISSUE TITLE
[BUG] Quest Tracker not showing Objectives to Players

### ISSUE THREAD

**Issue by Volksters** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#25]
**Module Version:** v0.7.10

**Describe the bug**
Quest Tracker does not show more than 1 objectives for players. GM can see all the objectives listed, but the players does not see anything. If 1 objective is showed to the players, it is available for the players. If 2 objectives are shown, the quest tracker becomes empty.

**To Reproduce**
1. Show all objectives to player as GM
2. From the player's view, open Quest Tracker

**Expected behavior**
Players should be able to see all the objectives listed in the Quest Tracker.

**Browser:**
 - 

**Foundry Version:** 
Version 10 Build 285

**Game System:** 
GURPS GGA

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by typhonrt** [comment]
Hi @Volksters. I'll look into things in more detail next week. I did verify while on the road just now that it does appear to be an issue, however I think it might be an issue w/ the Gurps system. When I did the `0.7.10` release so close to Foundry v10 "stable" I was only able to test w/ DnD5e system. I just installed Warhammer 40k, Twodsix, and The Dark Eye game systems and they don't have the same issue. 

So next week I'll look into more detail what might be going on w/ the Gurps system. It seems like the single press on the quest tracker / quest is just consumed / not activated for some reason and this could be due to something in the Gurps system for standard links. 

Nonetheless it looks like 10.285 release of Foundry added more compatibility warnings for an unused field in the FQL package manifest, so making a 0.7.11 release is going to happen just to fix that.

**Comment by BetoBadeira** [comment]
Hi, Just wanted to report that I have encounter similar issues with the L5R Game System, not even the GM is able to see the objectives or rewards on the quest.

Cheers,

**Comment by typhonrt** [comment]
Hi @BetoBadeira. Thanks for providing a tip of another system that isn't potentially working. On v8 / v9 I tested w/ the top 20 game systems and I don't believe L5R was on that list. I'll definitely take a peek into why Gurps / L5R may not be working. Initial indications do seem to point to something these systems may be doing regarding consuming clicks on Foundry styled anchor links otherwise this would be a problem for all game systems.

**Comment by typhonrt** [comment]
So I did find an issue in the Gurps system that was corrected though I also just worked around the issue w/ FQL. I also found an issue in the L5R system that I reported on their Gitlab repo and also worked around in FQL.

**Comment by typhonrt** [comment]
Hi folks... This issue is completed w/ the release of FQL `0.7.11`; while not a direct problem w/ FQL I worked around the system issues I found w/ Gurps & L5R and hardened FQL a bit more to potential systems misbehaving. Also reported the relevant issues to the system repos.
