### ISSUE TITLE
3.5e SRD incompatibility errors (Actual: A bug in 3.5 SRD system)

### ISSUE THREAD

**Issue by ilore** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#5]
If you are using 3.5e SRD system, this module shows (at least) two errors due some kind of incompatibility:

If you choose the option to let players drag the mission rewards and drop it to their character sheets, the rewards should disappear from the mission log and appear in the character sheet. Also, a message should appear in the GM screen about it. 

However, in the 3.5 SRD system, if a player drags and drops a reward, it still remains in the mission log and the player can drag and drop it multiple times, creating copies of the rewards. Also, none message appears in the GM screen about it.

**Comment by typhonrt** [comment]
Hi @ilore thanks for submitting this issue. Please see #1 regarding FQL going into maintenance mode. I'm releasing a continuation of the quest log as a new module with significantly upgraded tech hopefully before the v9 launch of Foundry around the beginning of the new year. There will be an easy upgrade path. There likely will be few if any additional releases of FQL. It's rock solid right now.

I did however investigate this issue as of course it affects FQL and the new quest log. It turns out that the D35E game system does not call the super method for `_onDrop` in the base Foundry ActorSheet which it extends. The hook that the quest log uses to implement removing the item and posting the notification fires in the parent / Foundry ActorSheet base class. 

You can see the _onDrop implementation in the D35E code here and notice that `super._onDrop` is not invoked:
<https://github.com/Rughalt/D35E/blob/master/module/actor/sheets/base.js#L2382>

So technically it is an oversight / issue w/ D35E by not deferring to the base class implementation of ActorSheet. That or if a wholly custom implementation is necessary then D35E should explicitly fire the same hooks as the base ActorSheet class which it doesn't presently. So FQL or any other module that depends on the `dropActorSheetData` hook will fail to work. 

Not really anything I can do on the FQL / quest log side of things except post a bug / issue in the D35E repo. 

Thanks for finding this though! Erg... I wonder how many other game systems this may do a similar thing / cause the same issue.

Alas right now just disabling drag & drop for rewards until a fix is in place with the D35E game system is pertinent.

**Comment by typhonrt** [comment]
@ilore; good news... Looks like Rughalt just addressed the issue with D35E game system, so hopefully in the next release of D35E things will work correctly. Do keep in touch after the next update to the system if the problem persists.

For the time being I'm going to close this issue.
