### ISSUE TITLE
Show All and Unlock All buttons doubling as Hide All and Lock All buttons.

### ISSUE THREAD

**Issue by Xystem4** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#61]
It seems like it would be a useful functionality if the "show all" and "unlock all" buttons for quest rewards changed into their opposite versions, "hide all", and "lock all", if all rewards are already visible/unlocked respectively.

Similar to how in text editors if you highlight multiple lines of text and press the "bulleted list" option (or similar), all lines become bulleted, which also happens if you press the option while highlighting a mix of bulleted and unbulleted lines, but if highlighting _only_ bulleted lines, it instead _removes_ the bullets.

**Comment by typhonrt** [comment]
Yeah.. I definitely thought about adding that in, but it was just a bit more to do when I was on a tight window to get the release out. The only thing I'd say though from a user perspective is that I wouldn't imagine this would be a often used feature. Either you are going to show all rewards at the beginning for a quest or hide most or all rewards and reveal them at the end of a quest. When GMs drop rewards items into this section they are hidden and locked by default. The "show all" / "unlock all" idea is to be able to quickly show all hidden rewards at the end of a quest; likewise with unlock all instead of having to individually click multiple buttons to show / unlock. The implementation of making the button hide all / lock all when all rewards are in the proper state is not too hard to pull off and a good task, but maybe not as practical of a use case from a usability angle. But indeed a good eye to see the possibility!

**Comment by anthonyronda** [comment]
@LukeLavan mentioned @Xystem4 wants to explore this further

**Comment by typhonrt** [comment]
Released with `0.7.6` which is available now.
