### ISSUE TITLE
general improvements to visuals of manual reordering of quest objectives/rewards

### ISSUE THREAD

**Issue by jinh5** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#63]
When moving the objective or reward bars the cursor flickers between the image of an arrow and a circle with a line through it constantly when it moves. Also the whole bar should be visible when moving the objective/rewards, not just the arrows on the side. I think instead of just clicking and dragging the arrows on the right side of the bar it would be more visually coherent to allow anywhere on the objective/reward bar to be clicked and dragged. Perhaps having a highlighted border around the box as it is being moved would help, similar to how the arrows turn orange when a bar is moved.

**Comment by typhonrt** [comment]
Hi @jinh5. Thanks for writing in this enhancement. We'll look into it, but do notice the same thing happens on any drag / drop action even in Foundry / system actor sheets when dragging items around / over actor sheets; tested this w/ D&D 5e system. It should be possible to display proper move cursor icons to show internally to FQL though.

**Comment by typhonrt** [comment]
So taking a look into reasons for the visual "glitches" or circle w/ a slash through it. This is an artifact of the drag / drop system when hovering over an element that doesn't have any drag / drop handling. There actually is a very easy one line JQuery callback that can be attached to all elements of a given window / app which prevents the circle w/ slash appearing when hovering over the element. There doesn't seem to be any negative side effects from adding this event callback. 

`html.on('dragenter', (event) => event.preventDefault());` 

This is added in `QuestPreview.activateListeners`. It should be further refined to with a constant added to the jquery events defined in `./src/model/constants.js`:
`html.on(jquery.dragenter, (event) => event.preventDefault());` 

As far as setting a different element as the drag image rather than just the move arrow icon. This can be accomplished by: 
`event.originalEvent.dataTransfer.setDragImage(li, 790, 20);` 
in `HandleDetails.taskDragStartSort`. Though the x / y offset must be variable as the QuestPreview window can be enlarged.

The above provides some implementation details, but certainly need to be fine tuned.

**Comment by typhonrt** [comment]
Upon further review while it would be nice to have the full `li` element be the drag image for the move task / reward action it turns out that by the rendering of the status icons creates an awkward ghosting effect:
![image](https://user-images.githubusercontent.com/311473/127250550-50ca6014-0582-47e6-bb4c-b14508f7a73d.png)

A potential solution to that is to clone the element / remove the icons and such, but it's more of a hack to pull this off than it seems worth it. 

I did add the simple dragenter handler which does prevent the circle / slash icon from showing in the QuestLog / QuestPreview UI when dragging inside the app.

**Comment by typhonrt** [comment]
Released with `0.7.6` which is available now.
