### ISSUE TITLE
Quest Tracker cannot be closed [BUG]

### ISSUE THREAD

**Issue by JordanRR** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#7]
**Module Version:** v0.7.9

**Describe the bug**
Once the quest tracker is opened, the window cannot be closed. I tried deactivating and the reactivating the module, but the window stays and is still impossible to close.

**To Reproduce**
1. Open Quest Tracker from the left pane.
2. Try to close the Quest Tracker by clicking the X.
3. See error.

**Expected behavior**
The window should close.

**Screenshots**

**Browser:**
 - Brave

**Foundry Version:** 
0.8.9

**Game System:** 
Old-School Essentials

**Additional context**
Hosted on The Forge

Active Modules:
----------
Chat Message Accessibility Indicators v1.0.0;
Chat Portrait v0.5.27;
Combat Tracker Effect Icon Tooltips v2.0.0;
Compendium Folders v2.3.64;
DF Chat Enhancements v3.5.1;
DF Quality of Life v1.6.1;
DFreds Droppables v1.4.0;
DF Scene Enhancement v3.4.2;
Dice So Nice! v4.2.2;
Dice Tray v1.3.2;
Drag Ruler v1.9.0;
Forien's Quest Log v0.7.9;
GM Notes v0.4.1;
GM Screen v2.9.0;
Illandril's Chat Enhancements v1.2.3;
Illandril's Token HUD scaler v1.4.2;
Inline Table Rolls v0.0.4;
Keybind Lib v0.3.4;
Less Fog v0.9.0;
lib - Color Settings v2.8.1;
Library: Chat Commands v1.4.0;
libWrapper v1.11.0.1;
Multilevel Tokens v1.5.2;
Perfect Vision v2.10.8;
Permission Viewer v0.8.14;
Pin Cushion v1.5.0;
Pings v1.2.12+0.8.6;
Quick Insert - Search Widget v2.5.3;
Scene Defaults v1.0.4;
Settings Extender v1.2.0;
Simple Calendar vv1.3.75;
SmallTime v1.13.7;
Smart Target v0.6.7;
socketlib v1.0.9;
Tidy UI - Game Settings v0.1.28;
Tokenizer v3.5.0;
TorchLight v0.10.0;
Window Controls v1.5.3;

Inactive Modules:
----------
About Time v1.0.6;
Babele v2.1.3;
Better Roofs v1.3.6;
Cautious Gamemaster's Pack v0.5.1;
Deepflame's Chat Cards v1.2.2;
DF User Logger v1.6.4;
Find the culprit v1.4.0;
Fog Manager v1.0.4;
FoundryVTT Arms Reach v2.1.6;
fr-FR - Core Game v0.7.9.0;
Levels v1.9.9.7;
Old School Essentials OGL Content v0.5.1;
PDFoundry v0.8.10;
Polyglot v1.7.28;
Token Mold v2.14.0;
Trigger Happy v0.8.25;
Wall Height v3.6.0.1;

**Comment by typhonrt** [comment]
Hi @JordanRR; thanks for posting an issue. Check that `Window Controls` is working as intended and not pinning the quest tracker. Someone else just recently wrote the exact same issue essentially on Forien's defunct / old repo for FQL. This is the correct repo for the maintained version of FQL, but review that [issue here](https://github.com/Forien/foundryvtt-forien-quest-log/issues/128):

You are running a lot of modules, so whenever you find an issue especially with FQL since it is in a rather solid place right now try disabling all modules except FQL or whatever module you need to verify that is working.

**Comment by JordanRR** [comment]
Thank you for the very quick response. It looks like Windows Control is the culprit, si I will notify them. 

I wish you a happy new year!
