### ISSUE TITLE
Automatically place new quests in the tab they were created in

### ISSUE THREAD

**Issue by Xystem4** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#72]
The "Add new Quest" button appears at the bottom of every tab of the quest log (for the GM), but will always place the new quest in the "Inactive" tab, which I at least found quite counterintuitive. If I go to the "Available" tab, and create a new quest, and then don't see it listed there, my first thought is that the quest didn't get created, not that it went to the "Inactive" tab.

If not simply adding the quest to the tab from which the "Add new Quest" button was clicked, giving an option in the creation menu to set the starting status would also be an improvement. (functioning similarly to the icons changing the state currently, except that they don't currently appear when first creating the quest).

**Comment by LukeLavan** [comment]
Relevant snippet of code: https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/blob/5478d0ef5f884a63b406e4e0e0ce6e59af153a27/templates/partials/quest-preview/details.html#L199-L203

**Comment by lyndseytoft** [comment]
I would like to be assigned to this one! :D

**Comment by typhonrt** [comment]
Well... This doesn't make sense if the tabs are completed / failed. The way this currently works is that for GM and soon trusted players who have full editing of quests that they appear in `inactive`. For players that add new quests they always appear in 'available'. Players do no not have access to the inactive tab. I suggest a possible solution is for GM / trusted player added quests to show a combo box in the QuestForm to choose 'inactive' or 'available' with it defaulting to 'inactive'. For normal players who add quests they always should go to 'available'.

**Comment by LukeLavan** [comment]
I agree that it doesn't make sense for the completed/failed tabs; does it make more sense to remove the 'Add new Quest' button from these tabs? Alternatively, is it possible to have the combo box default be the tab from which the QuestForm was opened?

I agree with @Xystem4 that having to look for the quest after creating it is awkward and not immediately seeing it when the QuestForm is closed gives the impression that the quest was not created if I wasn't already aware that they all go to a different place by default. Personally, I would rather look for the button to create a quest than look for the quest after it was created.

**Comment by typhonrt** [comment]
Defaulting to inactive makes sense when creating new quests especially if during a campaign / live in game since the new quest form isn't necessarily complete as it lacks objectives and rewards. I do think just having a combo box with the category the new quest will be put in is best with inactive as default. And it doesn't make sense to duplicate QuestPreview for new quest data entry. QuestPreview is a complicated beast. 

It should be noted QuestForm functions differently in that it doesn't save data when editing the different fields and only creates the journal entry / backing data store when the user clicks on 'add to quest log'

I just added a UI notification when a quest is added with the name and category. That should alleviate any confusion. I gather most folks that use FQL know that a quest goes to the inactive category when created.

I think as far as the 'add new quest' button that it should be removed and an icon placed on the top bar to the right of the quest category of the main quest log section. 

I also have made great progress with the in memory DB. A bit to discuss there in another forum.

**Comment by typhonrt** [comment]
So I have made the big workflow change and removed QuestForm. QuestPreview pops up right away w/ full quest editing. This does create a quest immediately, so it's important to put new quests in 'inactive' for GMs / trusted player edit. The tab switches to 'inactive' on quest add. Try out the changes. It's quite streamlined. The add button is gated and requires the recent / newly added quest to have it's QuestPreview window closed before the next quest is created. UI notifications display informing the user what is occuring.  For players that can create quests it only makes sense for them to go to the 'available' tab, but like the GM this tab is automatically selected when a player creates a quest.

**Comment by LukeLavan** [comment]
The newest version automatically switches the active quest log tab to the tab that the new quest was placed in. I think that this issue should be closed with these changes.

**Comment by typhonrt** [comment]
Shipped in `0.7.4` which is now available.
