### ISSUE TITLE
Spell Rewards - select form

### ISSUE THREAD

**Issue by BL4KANG3L** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#90]
When dragging in spells as rewards let DM decide if this will be a spell scroll for Inventory or a spell for Spellbook

**Comment by typhonrt** [comment]
That's a tough one insofar that it is very system specific. I gather you might have D&D5e in mind for this idea. It could be something the system can implement as it is a drop action into the actor sheet that occurs. There is a possibility as well for another module that works in tandem with the system I suppose that reacts to the drop event and adds the options or if there is anything specific that needs to be embellished on the data sent to the actor sheet for a given system can enhance the data stored or transferred to the actor sheet. 

So again a tough one because nothing system specific should be added to FQL, but there may be ways through hooks or other means to allow another module to enhance the data transferred to the actor sheet.

**Comment by typhonrt** [comment]
So indeed.. I'm going to mark this one 'invalid'.  Not that your suggestion was bad. FQL works just like dragging items from the compendium or other world source. It's up to the player to drag the item to the spell book or to the actor sheet as a consumable. I suppose the GM should check up and make sure they put it in the right space if they are worried. There is no way to enforce the drop target without doing system dependent actions which FQL has to stay 100% neutral in this regard.
